import './globals.css'
import { Geist } from "next/font/google";
import { cn } from "@/styles/lib/utils";
import { Metadata } from 'next';

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
    title:"lampngia - Portfolio",
    description:"Generated by lampngia"
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={cn("font-sans", geist.variable)}>
            <body>{children}</body>
        </html>
    );
}
